#!/bin/sh
### BEGIN INIT INFO
# Provides: archery-led-display
# Required-Start:   $network
# Required-Stop:    
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:    archery-led-display server
# Description:          An open-source server for controlling LED-Panels
### END INIT INFO

NAME=archery-led-server
DAEMON=/usr/local/sbin/led-server
PIDFILE=/var/run/led-server.pid
SCRIPTNAME=/etc/init.d/$NAME

. /lib/lsb/init-functions

# Actions
case "$1" in
    start)  log_daemon_msg "Starting led-server" "archery-led-display"
            start_daemon -p $PIDFILE $DAEMON
            log_end_msg $?
            ;;

    stop)   log_daemon_msg "Stopping led-server" "archery-led-display"
            killproc -p $PIDFILE $DAEMON
            RETVAL=$?
            [ $RETVAL -eq 0 ] && [ -e $PIDFILE ] && rm -f $PIDFILE
            log_end_msg $RETVAL
            ;;
    restart)    log_daemon_msg "Restarting led-server" "archery-led-display"
                $0 stop
                $0 start
                ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
    *)  log_action_msg "Usage: /etc/init.d/archery-led-display {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0